import { NextRequest, NextResponse } from "next/server"

// ── Parejas ──────────────────────────────────────────────────────────────────

const VERDADES_PAREJAS: string[] = [
  "¿Cuál es tu recuerdo favorito de nuestra relación hasta ahora?",
  "¿En qué momento supiste que yo era especial para ti?",
  "¿Qué es lo primero que pensaste cuando me viste por primera vez?",
  "¿Qué es lo que más te gusta de mí?",
  "¿Cuál ha sido tu momento más vergonzoso conmigo?",
  "¿Qué es lo que nunca me has contado pero querías hacerlo?",
  "¿Qué canción te recuerda a mí y por qué?",
  "¿Cuál es la cosa más ridícula que has hecho por amor?",
  "¿Si pudieras cambiar algo de nuestra relación, qué sería?",
  "¿Qué sueño tienes que aún no le has contado a nadie?",
  "¿Qué es lo que más te pone nervioso/a de mí?",
  "¿Cuál es el recuerdo de nuestra primera cita que más te hace reír?",
  "¿Qué 3 palabras usarías para describir nuestra relación?",
  "¿Qué cosa te da más vergüenza admitir que te gusta?",
  "¿En qué momento has sido más feliz en tu vida?",
  "¿Qué es lo que más extrañas de tu infancia?",
  "¿Qué es lo que te hace sentir amado/a de verdad?",
  "¿Cuál es tu plan perfecto para una cita romántica?",
  "¿Qué es lo que más te cuesta pedir perdón?",
  "¿Cuál es tu mayor miedo y cómo lo llevas?",
  "¿Qué harías si solo te quedara un día de vida?",
  "¿Qué mensaje me enviarías si supieras que es el último?",
  "¿Si pudieras volver atrás en el tiempo, qué momento vivirías de nuevo?",
  "¿Qué promesa quieres que nos hagamos hoy?",
  "¿En qué momento has sentido más orgullo de ti mismo/a?",
  "¿Qué hábito tuyo crees que a mí más me cuesta tolerar?",
  "¿Qué es lo que más admiras de mí?",
  "¿Hay algo que hayas querido preguntarme y no te hayas atrevido?",
  "¿Cuándo fue la última vez que lloraste y por qué?",
  "¿Qué significa para ti que sigamos juntos dentro de 10 años?",
  "¿Qué persona (además de mí) ha marcado más tu vida?",
  "¿Cuál es tu peor manía o hábito?",
  "¿Qué película o serie me recomendarías para entenderme mejor?",
  "¿Qué es lo que más te tranquiliza cuando estás estresado/a?",
  "¿Qué harías con un millón de euros?",
  "¿Cuál es tu mayor arrepentimiento?",
  "¿Qué superpower elegirías si pudieras tener uno?",
  "¿Si pudieras vivir en cualquier ciudad del mundo, cuál elegirías y por qué?",
  "¿Cuál es tu tipo de vejez ideal?",
  "¿Cuándo fue la primera vez que te sentiste verdaderamente enamorado/a?",
  "¿Qué es lo que más valoras en una persona?",
  "¿Cuál es el cumplido que nunca olvidarás?",
  "¿Qué cosa tuya crees que me sorprendería si la descubriera?",
  "¿Cuál es tu forma favorita de demostrar que quieres a alguien?",
  "¿Hay algo que sientas que nunca entenderé de ti?",
  "¿Qué es lo que más te cuesta en una relación?",
  "¿Qué es lo que más te gusta de ti mismo/a?",
  "¿A qué persona famosa te gustaría parecerte y por qué?",
  "¿Cuál es la decisión más difícil que has tomado en tu vida?",
  "¿Qué es lo que te hace único/a?",
  "¿Qué es lo que te gustaría que la gente dijera de ti cuando no estás?",
  "¿Cuándo te sentiste más solo/a en tu vida?",
  "¿Cuál es la mentira más grande que has dicho?",
  "¿Qué harías diferente si pudieras vivir tu adolescencia de nuevo?",
  "¿Qué es lo que más te ha enseñado nuestra relación?",
  "¿Qué es lo que más te gusta de cómo te trato?",
  "¿Cuál es tu miedo más irracional?",
  "¿Qué es lo que te hace reír hasta llorar?",
  "¿Cuál es el momento más romántico que has vivido?",
  "¿Cuál es la conversación más importante que hemos tenido?",
  "¿Qué cosa de mí te enamoró sin que te dieras cuenta?",
  "¿Cuántos hijos te gustaría tener o no tener, y por qué?",
  "¿Cuál es tu recuerdo más feliz de la infancia?",
  "¿Qué es lo que más te gusta de cómo nos llevamos?",
  "¿Cuál sería tu lugar perfecto para vivir juntos?",
  "¿Cuál es la aventura que más te gustaría vivir conmigo?",
  "¿Qué es lo que nunca renunciarías por nadie?",
  "¿Cuándo sentiste que de verdad me conocías?",
  "¿Qué es lo que más disfrutas de pasar tiempo conmigo?",
  "¿Cuál es tu mayor logro personal hasta ahora?",
  "¿Qué cosa pequeña hago que te alegra el día sin que yo lo sepa?",
  "¿Qué hobby secreto tienes o te gustaría tener?",
  "¿Cuándo fue la última vez que hiciste algo por primera vez?",
  "¿Qué es lo que más extrañarías de mí si no estuviera?",
  "¿Cuándo sentiste que nuestra relación dio un salto importante?",
  "¿Qué cosa de ti mismo/a llevas más tiempo intentando mejorar?",
  "¿Cuál es la tradición familiar que más quieres mantener?",
  "¿Qué canción pondría la banda sonora de tu vida ahora mismo?",
  "¿Qué es lo que más te cuesta decirme?",
  "¿Cuál sería tu último deseo si pudieras pedir uno?",
  "¿Qué cosa me dirías si supieras que no te voy a juzgar?",
  "¿En qué crees que somos completamente opuestos?",
  "¿Qué es lo que más valoras de nuestra convivencia?",
  "¿Hubo un momento en que dudaste de nuestra relación? ¿Qué lo cambió?",
  "¿Qué es lo que más te cuesta aceptar de cómo soy?",
  "¿Qué le dirías a tu yo del pasado sobre mí?",
  "¿Cuál es el detalle más pequeño que he tenido contigo y que nunca olvidarás?",
  "¿Qué haríamos diferente si empezáramos nuestra relación hoy?",
  "¿Qué es lo que te enamora de mí cada día?",
  "¿Cuándo fue la última vez que sentiste que me necesitabas de verdad?",
  "¿Qué es lo que más te da seguridad en nuestra relación?",
  "¿Cómo te imaginas que seremos dentro de 20 años?",
  "¿Qué es lo que más te cuesta perdonarme cuando me equivoco?",
  "¿Hay algo de tu pasado que crees que afecta a nuestra relación?",
  "¿Qué es lo que más te sorprendió de enamorarte de mí?",
  "¿Qué harías si descubrieras que tengo un secreto que te afecta?",
  "¿Cuál es el sacrificio más grande que has hecho por nosotros?",
  "¿Qué es lo que más te gusta de cómo discutimos y nos reconciliamos?",
  "¿Qué aventura o experiencia quieres que hagamos juntos antes de que acabe el año?",
  "¿Qué es lo que más te asusta del futuro juntos?",
  "¿Cuándo fue el momento en que más me has querido proteger?",
]

const RETOS_PAREJAS: string[] = [
  "Imita la voz de tu pareja durante 1 minuto",
  "Cuéntale a tu pareja algo que nunca le hayas dicho",
  "Da a tu pareja el masaje de espalda más increíble de su vida",
  "Baila una canción romántica durante 30 segundos sin parar",
  "Dibuja un retrato de tu pareja en solo 60 segundos",
  "Di 5 cosas que amas de tu pareja SIN repetirte",
  "Imita a tu pareja haciendo algo cotidiano hasta que adivine qué es",
  "Describe nuestra relación usando solo emojis",
  "Haz una pose de modelo durante 10 segundos sin reírte",
  "Dile algo cursi que normalmente no dirías",
  "Haz la actuación más dramática posible de 'te quiero'",
  "Explica en 60 segundos por qué te enamoraste de tu pareja",
  "Inventa una canción de 30 segundos sobre vuestra historia",
  "Recita un poema improvisado para tu pareja ahora mismo",
  "Muestra la foto más graciosa que tengas en tu teléfono",
  "Habla con acento diferente durante 2 minutos completos",
  "Escribe con el dedo un mensaje secreto en la espalda de tu pareja",
  "Declara tu amor en silencio, solo con gestos, durante 30 segundos",
  "Haz el gesto más ridículo que sepas hacer",
  "Di el alfabeto pero cada letra es una cosa que te gusta de tu pareja",
  "Silba tu canción favorita hasta que tu pareja la adivine",
  "Inventa un nombre para el equipo que formáis los dos y explica por qué",
  "Muestra tu cara de enfado más convincente durante 20 segundos",
  "Confiesa una mentira pequeña que le hayas dicho alguna vez",
  "Dile a tu pareja tres cosas que te gustaría que hiciera más seguido",
  "Enumera 10 cosas que os hagan reír a los dos",
  "Llama a alguien de tu familia y dile que lo quieres de parte de los dos",
  "Crea una frase de amor usando solo palabras de 3 letras",
  "Propón un plan sorpresa para el próximo fin de semana",
  "Cuenta en 1 minuto cómo sería vuestro día perfecto juntos",
  "Envíale un audio muy dramático a alguien de tu familia diciéndoles que los quieres",
  "Describe nuestra relación como si fuera la sinopsis de una película",
  "Di 10 cosas que admiras de tu pareja sin repetir nada",
  "Pon una canción que os represente como pareja y explica por qué",
  "Imita al personaje de tu película favorita durante 30 segundos",
  "Comparte el meme más gracioso que tengas guardado",
  "Haz 10 flexiones o sentadillas ahora mismo",
  "Di tres cosas que harías diferente si tuvieras que enamorarte de cero",
  "Imita a un famoso/a que le guste a tu pareja",
  "Cuéntale la historia de cómo os conocisteis con todos los detalles dramáticos",
  "Haz una foto artística de lo que tengas más cerca ahora mismo",
  "Escribe en papel la lista de las 5 cosas que más amas de tu pareja y dásela",
  "Di el nombre de tu pareja con 5 acentos diferentes",
  "Inventa un eslogan para vuestra pareja como si fueran una marca",
  "Canta los primeros 30 segundos de vuestra canción favorita",
  "Haz una parodia de cómo me comporto cuando estoy enfadado/a",
  "Cuenta un secreto tonto que nunca le hayas contado a nadie",
  "Haz el baile más ridículo que conozcas durante 15 segundos",
  "Di tres cosas que quieres que hagamos juntos antes de que acabe el año",
  "Recrea la escena más romántica de tu película favorita",
  "Describe a tu pareja como si fuera un plato de restaurante con estrellas Michelin",
  "Muéstrame cómo bailarías si estuvieras solo/a en casa",
  "Llora de forma teatral durante 20 segundos sin motivo",
  "Inventa tres apodos nuevos para tu pareja ahora mismo",
  "Haz una declaración de amor usando solo palabras que empiecen por la misma letra",
  "Convence a tu pareja en 30 segundos de que eres la mejor persona del mundo",
  "Cuéntame tu primer recuerdo de mí con todo lujo de detalles",
  "Actúa como si fueras el protagonista de una telenovela durante 1 minuto",
  "Haz una lista de 5 tradiciones nuevas que quieres empezar con tu pareja",
  "Imita cómo habla tu pareja por teléfono",
  "Describe nuestra primera cita como si fuera un anuncio de televisión",
  "Crea un brindis especial para vosotros ahora mismo",
  "Di tres cosas que nunca te cansarías de hacer con tu pareja",
  "Escenifica cómo pedirías matrimonio sin palabras",
  "Inventa un chiste sobre vuestra relación que sea tan malo que sea bueno",
  "Haz una reverencia real como si tu pareja fuera la realeza",
  "Cuéntame tu sueño más raro que recuerdes",
  "Di en voz alta qué es lo que más te gusta del físico de tu pareja",
  "Imita a tu pareja cuando le hablas a las mascotas o a los bebés",
  "Propón un viaje improvisado para el próximo mes con destino sorpresa",
  "Explica por qué eres la mejor pareja del mundo en exactamente 10 palabras",
  "Recita los votos de boda más cursis que puedas imaginar",
  "Cuéntame la historia de nuestra relación al revés, desde hoy hasta el principio",
  "Diseña con mímica el logo de vuestra pareja",
  "Haz la voz de un presentador de concurso y presenta a tu pareja al público",
  "Di cuánto quieres a tu pareja usando solo números y porcentajes",
  "Toca con el dedo el ritmo de una canción hasta que tu pareja la adivine",
  "Cuenta en 60 segundos por qué vuestra historia merece una película",
  "Haz la imitación de tu pareja cuando está nervioso/a",
  "Pon cara de enamorado/a durante 20 segundos sin reírte",
  "Inventa el menú de vuestro restaurante favorito imaginario",
  "Explica por mímica cómo fue vuestro primer beso",
  "Di tres cualidades de tu pareja que antes no apreciabas y ahora sí",
  "Escríbele un mensaje de texto de amor desde el otro lado de la habitación",
  "Haz el sonido de 3 cosas que asocias con tu pareja",
  "Recita el discurso de boda que le darías ahora mismo",
  "Describe el olor de tu pareja con 5 palabras poéticas sin que sea raro",
  "Cuenta en voz alta tu mayor miedo sobre perderme",
  "Haz la cara que pondrías si me propusiera algo muy inesperado",
  "Inventa un superhéroe cuyo poder sea algo que hace tu pareja muy bien",
  "Di el mayor defecto de tu pareja de la forma más adorable posible",
  "Crea una lista de los 5 momentos más importantes de vuestra historia",
  "Haz una imitación de ti mismo/a el día que te enamoraste",
  "Muéstrame cómo reaccionarías si te pidiera que te casaras conmigo ahora mismo",
  "Describe lo que más te gusta de despertar junto a tu pareja",
  "Di las 5 razones por las que nuestra relación es especial",
  "Haz el ruido que haría vuestra historia de amor si fuera una película de Hollywood",
]

// ── Neutral ───────────────────────────────────────────────────────────────────

const VERDADES_NEUTRAL: string[] = [
  "¿Cuál es tu mayor talento oculto?",
  "¿Qué harías si superas que no puedes fracasar?",
  "¿Cuál es la cosa más estúpida que has hecho por quedar bien?",
  "¿Qué es lo que más te arrepientes de no haber hecho?",
  "¿Cuántas veces has fingido entender algo que no entendías?",
  "¿Cuál es el insulto más creativo que has usado?",
  "¿Qué opinas realmente de las redes sociales?",
  "¿Qué personaje de serie o película crees que eres en la vida real?",
  "¿Cuál es el cotilleo más jugoso que sabes y no has contado?",
  "¿Qué harías diferente si pudieras vivir el último año de nuevo?",
  "¿Cuál es tu opinión más impopular?",
  "¿Cuál es la peor excusa que has puesto para no salir?",
  "¿Qué es lo que más te cuesta hacer por vergüenza?",
  "¿Cuál es tu mayor vicio inconfesable?",
  "¿Qué es lo más ridículo en lo que has gastado dinero?",
  "¿Qué asignatura del colegio odias que hayas tenido que estudiar?",
  "¿Cuál es la cosa más impulsiva que has hecho en tu vida?",
  "¿A quién le has mentido más recientemente y por qué?",
  "¿Cuál es el consejo que sigues sin entender bien por qué?",
  "¿Qué es lo que más te da pereza hacer aunque sabes que deberías?",
  "¿Cuál es la teoría de conspiración más absurda que te ha llegado a parecer creíble?",
  "¿Qué es lo que más envidias de alguien que conoces?",
  "¿Cuál ha sido tu mayor malentendido con alguien?",
  "¿Qué es lo primero que haces al despertar que no admitirias públicamente?",
  "¿Cuántas veces revisas el teléfono en una hora?",
  "¿Cuál es la canción más vergonzosa que tienes en tu lista de reproducción?",
  "¿Qué es lo más raro que comes o comes de forma rara?",
  "¿Cuál es la excusa más creativa que has inventado para no hacer algo?",
  "¿Qué es lo que más te molesta de la gente aunque no lo dices?",
  "¿A qué celebrity te gustaría parecerte y por qué?",
  "¿Cuál es la peor actuación que has dado en tu vida?",
  "¿Qué es lo que más tiempo procrastinas?",
  "¿Cuál ha sido tu mayor vergüenza en público?",
  "¿Qué ley cambiarías si pudieras?",
  "¿Qué es lo más caro que has roto y no lo has contado?",
  "¿Cuántas veces en serio has intentado aprender algo y lo has dejado a medias?",
  "¿Qué aplicación del móvil usas más de lo que admitirías?",
  "¿Cuál es la comida que comes a escondidas porque te da vergüenza que gusta?",
  "¿Qué deporte o hobby has intentado empezar más de 3 veces sin éxito?",
  "¿Cuál es tu recuerdo más embarazoso del colegio?",
  "¿Qué es lo que dices que odias pero en realidad disfrutas en secreto?",
  "¿Cuál es el reto que llevas años posponiendo?",
  "¿Qué harías si supieras que nadie te va a ver durante 24 horas?",
  "¿Cuál es la cosa más absurda que te ha dado miedo?",
  "¿Qué momento de tu vida cambiarías aunque nadie lo notara?",
  "¿Cuál es el comentario más hiriente que has recibido y que no puedes olvidar?",
  "¿Qué hábito saludable intentas adoptar y que siempre abandonas?",
  "¿Cuánto tiempo llevas sin leer un libro completo?",
  "¿Qué es lo más infantil que sigues haciendo?",
  "¿Cuál es la pregunta que más miedo te da que te hagan?",
  "¿Qué es lo que más te cuesta perdonar?",
  "¿Cuántas notificaciones no leídas tienes ahora mismo?",
  "¿Cuál es el trabajo que pensabas hacer de pequeño y que nunca harías ahora?",
  "¿Qué es lo que más te cuesta decirle a alguien a la cara?",
  "¿Cuál es la situación social que más te agota?",
  "¿Qué es lo que más te cuesta cuando estás de mal humor?",
  "¿Cuál es la serie que llevas empezada meses sin terminar?",
  "¿Qué es lo más raro que has buscado en internet?",
  "¿Cuál es tu fobia más irracional?",
  "¿Qué es lo primero en lo que te fijas cuando conoces a alguien?",
  "¿Cuántas horas a la semana sientes que has perdido el tiempo de verdad?",
  "¿Qué harías si tuvieras un día libre sin responsabilidades?",
  "¿Cuál es tu opinión sobre las reuniones de trabajo o estudio?",
  "¿Qué es lo que más echas de menos de cuando eras niño/a?",
  "¿Cuál es la mentira más creativa que has contado?",
  "¿Qué es lo que más te cuesta admitir que no sabes hacer?",
  "¿Cuál es el cumpleaños más importante que has olvidado?",
  "¿Qué es lo que más te distrae cuando deberías estar concentrado/a?",
  "¿Cuál es el consejo que das pero que tú mismo/a no sigues?",
  "¿Qué es lo que más te da vergüenza de ti mismo/a?",
  "¿Cuánto tiempo llevas sin hablar con alguien que considerabas amigo/a?",
  "¿Cuál es el plan que más veces has cancelado en el último año?",
  "¿Qué es lo que más tardas en decidir?",
  "¿Cuál es la decisión que tomaste sin pensar y que resultó ser la mejor?",
  "¿Qué es lo más caro que has comprado por impulso y arrepentido/a?",
  "¿Cuál fue la última vez que te equivocaste claramente y lo admitiste?",
  "¿Qué es lo que más te cuesta hacer aunque sabes que te haría bien?",
  "¿Cuál es la creencia que tenías de pequeño/a que hoy te parece absurda?",
  "¿Qué harías si encontraras 500€ en la calle?",
  "¿Cuál es el mayor riesgo que has tomado en tu vida?",
  "¿Qué cosa tuya sabes que irrita a los demás aunque no te lo digan?",
  "¿Cuál es el tema del que menos quieres hablar en una conversación?",
  "¿Qué es lo que más te cuesta compartir con desconocidos?",
  "¿Cuál es tu mayor inseguridad cuando estás en grupo?",
  "¿Qué harías si tuvieras poderes durante un solo día?",
  "¿Cuál es el sueño que recuerdas con más frecuencia?",
  "¿Qué película o serie te ha hecho llorar y niegas haberlo hecho?",
  "¿Cuál es tu teoría personal sobre el universo?",
  "¿Qué es lo más generoso que has hecho sin que nadie lo sepa?",
  "¿Cuánto tiempo llevas pensando en hacer algo que aún no has empezado?",
  "¿Qué es lo que más te cuesta delegar o pedir ayuda?",
  "¿Cuál es el comentario que guardas para ti pero que casi sueltas?",
  "¿Cuándo fue la última vez que hiciste algo que te daba miedo?",
  "¿Qué es lo que más te cuesta aceptar de cómo eres?",
  "¿Cuál es tu debilidad más conocida entre tus amigos?",
  "¿Qué es lo que más envidia sana te da de alguien?",
  "¿Cuál es la experiencia más fuera de tu zona de confort que has vivido?",
  "¿Qué cambiarías de ti mismo/a con un clic si pudieras?",
  "¿Cuál es el momento en que más has sentido que te has superado?",
]

const RETOS_NEUTRAL: string[] = [
  "Habla durante 1 minuto completo sin decir 'eeeh' ni 'mmm'",
  "Imita a un famoso/a hasta que alguien adivine de quién se trata",
  "Di el trabalenguas más largo que sepas sin equivocarte",
  "Haz la coreografía de un anuncio de televisión que todos conozcan",
  "Describe un color sin nombrarlo ni decir a qué objetos se asocia",
  "Convence al grupo de que eres un robot durante 2 minutos",
  "Haz una parodia de un presentador del tiempo con lo que ves por la ventana",
  "Di en 30 segundos todos los países de Europa que recuerdes",
  "Actúa como si estuvieras en una película de acción durante 1 minuto",
  "Haz el ruido de 5 animales sin repetirte",
  "Cuenta un chiste tan malo que provoque silencio incómodo",
  "Describe tu película favorita sin decir el título y que el grupo la adivine",
  "Haz mímica de un oficio o profesión hasta que alguien lo adivine",
  "Di el abecedario al revés en menos de 30 segundos",
  "Habla en otro idioma (o inventado) durante 1 minuto sin parar",
  "Representa una escena de película de terror sin sonido",
  "Di los nombres de 10 capitales de países en 20 segundos",
  "Haz de comentarista deportivo de algo mundano como servirse agua",
  "Imita cómo camina alguien del grupo hasta que adivinen quién es",
  "Canta una canción sustituyendo todas las vocales por la 'e'",
  "Haz el monólogo de un político inventado durante 45 segundos",
  "Da un discurso apasionado a favor de algo completamente absurdo",
  "Dibuja un autorretrato con los ojos cerrados",
  "Haz la cara de 5 emociones diferentes en 10 segundos cada una",
  "Describe un objeto de la habitación como si fuera una joya de museo",
  "Inventa el tráiler de una película con el peor título posible",
  "Convence al grupo de comprar algo completamente inútil",
  "Haz que el grupo se ría en menos de 30 segundos",
  "Recita los planetas del sistema solar de memoria",
  "Inventa un refrán nuevo que suene antiguo y sabio",
  "Di 10 palabras en inglés mientras alguien cuenta hasta 10",
  "Haz una coreografía de 30 segundos con la canción que te pongan",
  "Explica cómo funciona internet a alguien de 80 años (en 1 minuto)",
  "Cuenta hasta 30 alternando con otra persona sin que ninguno falle",
  "Muestra la pantalla de inicio de tu móvil sin esconder nada",
  "Haz que parezca que estás hablando por teléfono con el presidente",
  "Describe tu día de hoy como si fuera una épica aventura medieval",
  "Di un piropo inventado y creativo a alguien del grupo",
  "Cuenta el argumento de un libro inventado que suene muy profundo",
  "Haz el doblaje de alguien del grupo durante 30 segundos",
  "Inventa un titular de periódico sobre algo que ha pasado hoy",
  "Di 5 cosas que harías si fueras invisible durante un día",
  "Haz que el grupo adivine una película solo con sonidos",
  "Inventa un trabalenguas nuevo en este momento",
  "Explica qué es un smartphone a alguien de la antigüedad",
  "Haz el personaje más dramático posible con una situación cotidiana",
  "Actúa como si llevaras 10 años sin ver a alguien del grupo",
  "Haz de chef estrella explicando cómo preparas un bocadillo",
  "Di el nombre de 10 frutas haciendo el sonido de cada una",
  "Convierte una noticia aburrida en algo emocionante en 45 segundos",
  "Haz una entrevista de trabajo a alguien del grupo para un trabajo absurdo",
  "Sé el presentador de un programa de teletienda con un objeto de la sala",
  "Imita el sonido de una tormenta usando solo partes de tu cuerpo",
  "Da un discurso de agradecimiento por ganar un Oscar por lavarte los dientes",
  "Convierte una receta de cocina en una canción de reggaeton",
  "Recita un poema espontáneo sobre el sofá o la silla en la que estás",
  "Haz de árbitro de un partido de fútbol de lo que sea que esté pasando",
  "Inventa tres nombres de productos de farmacia que suenen reales",
  "Haz mímica de un momento vergonzoso sin decir lo que es",
  "Explica cómo sobrevivir en una isla desierta con lo que tienes en los bolsillos",
  "Di 15 palabras que rimen con 'amor' en menos de 20 segundos",
  "Actúa como si el suelo fuera lava durante 30 segundos",
  "Haz de guía turístico de la habitación en la que estáis",
  "Di los ingredientes de una receta imposible que suene deliciosa",
  "Cuenta tu día de hoy como si fuera un capítulo de serie de suspense",
  "Haz que alguien del grupo se ría sin hacerle cosquillas",
  "Inventa un superpoder inútil y explica para qué serviría",
  "Habla durante 30 segundos sin usar la letra 'a'",
  "Haz el comentarista de un concurso de belleza con objetos de la habitación",
  "Di en qué película serías el primero en morir y por qué",
  "Actúa como si fueras el villano de una película de Disney durante 1 minuto",
  "Haz la voz de un locutor de radio de los años 80 hablando de lo que quieras",
  "Inventa un produto de limpieza con nombre en latín y explica sus beneficios",
  "Crea el jingle publicitario de algo que no se puede anunciar",
  "Haz de embajador/a de un país imaginario y da un discurso",
  "Describe tu almuerzo de hoy como si fuera un plato de alta cocina",
  "Actúa como si fueras un robot que acaba de descubrir las emociones",
  "Inventa tres leyes absurdas que mejorarían el mundo",
  "Haz la parodia de un tutorial de YouTube sobre algo que no sabes hacer",
  "Di los meses del año pero en orden alfabético",
  "Inventa el nombre de una banda de música y el título de su primer álbum",
  "Haz el monólogo de alguien que acaba de sobrevivir a un atasco de tráfico épico",
  "Da instrucciones para hacer algo cotidiano como si fuera un manual de IKEA",
  "Imita cómo explica algo una persona cuando no tiene ni idea del tema",
  "Inventa una leyenda urbana sobre el lugar donde estáis ahora",
  "Haz de periodista entrevistando a la persona más aburrida del mundo",
  "Cuenta un cuento para niños con personajes completamente inapropiados",
  "Di el discurso motivacional más absurdo que hayas oído",
  "Haz el doblaje de un documental sobre alguien del grupo",
  "Inventa tres emojis que deberían existir y no existen",
  "Haz una lista de las 5 mejores pelis de ciencia ficción protagonizadas por verduras",
  "Explica la teoría de la relatividad usando solo monosílabos",
  "Di 10 onomatopeyas distintas en 15 segundos",
  "Actúa como si fueras el narrador de un partido de fútbol y el balón fuera un sándwich",
  "Inventa un trabalenguas con el nombre de alguien del grupo",
  "Haz de crítico literario describiendo el último mensaje que mandaste por WhatsApp",
  "Di el discurso más emocionante posible sobre por qué el agua es el mejor invento",
  "Imita a tres políticos/famosos en menos de 1 minuto",
  "Haz de detective investigando por qué hay un calcetín en el suelo",
  "Inventa una excusa brillante para llegar tarde que nadie haya usado nunca",
]

// ── Helpers ───────────────────────────────────────────────────────────────────

function pick<T>(arr: T[], n: number): T[] {
  const copy = [...arr]
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]]
  }
  return copy.slice(0, Math.min(n, copy.length))
}

export async function GET(req: NextRequest) {
  const type     = req.nextUrl.searchParams.get("type")     ?? "truth"
  const category = req.nextUrl.searchParams.get("category") ?? "parejas"
  const count    = Math.min(parseInt(req.nextUrl.searchParams.get("count") ?? "20"), 30)

  let pool: string[]
  if (type === "truth") {
    pool = category === "neutral" ? VERDADES_NEUTRAL : VERDADES_PAREJAS
  } else {
    pool = category === "neutral" ? RETOS_NEUTRAL : RETOS_PAREJAS
  }

  return NextResponse.json({ source: "api", questions: pick(pool, count), type, category })
}
